
.onLoad = function(libname, pkgname) {
#
# this is for repositioning in packages generated by externalize()
# this comes from GGtools inst/extpacksupp/zzz.R
#
# if you want to get the expression data loadable
# at load time, use the namespace manipulations commented
# out below, but getSS then needs to be changed
#
# to avoid confusion the name of ExpressionSet should start with a "."
# if we do this
#
#  ns = asNamespace(pkgname)
  cn = gsub(".rda", "", dir(system.file("parts",
     package=pkgname)))
#  clnpack = gsub("Pack", "", pkgname)
#  obname = paste(clnpack, "Ex", sep="")
#  eset = get(load(system.file("data/eset.rda",
#     package=pkgname)))
#  assign(obname, eset, envir=ns)
#  namespaceExport(ns, obname)
  packageStartupMessage(paste("To get a tailored smlSet, use getSS(\"",
   pkgname, "\", [chrvec])", sep=""), "\n")
  packageStartupMessage("available chromosomes are named ",
        paste(selectSome(cn), collapse=", "), "\n")
}

.onAttach <- function(libname, pkgname) {
    msg <- sprintf(
        "Package '%s' is deprecated and will be removed from Bioconductor
         version %s", pkgname, "3.14")
    .Deprecated(msg=paste(strwrap(msg, exdent=2), collapse="\n"))
}
